In [26]:

import numpy as np
import pandas as pd

from src.scripts import Runner
from src.clients.backtester_client import BacktesterClient
from src.strategies.macd import MACDStrategy
from src.strategies.nothing import NothingStrategy
from src.strategies.reversals import ReversalsStrategy
from src.strategies.support_resistance import SupportResistance

from src.indicators.extremum import Max, Min
from src.indicators.optimum import Support, Resistance
from src.indicators.candlestick import Hammer

In [12]:
data = pd.read_csv("data.csv", index_col=0)
data.index = pd.to_datetime(data.index)

In [22]:
data['y'] = data['close'].shift(-5)
data

,time,open,high,low,close,volume,y
2022-08-22 06:30:00,1.661139e+09,21474.89,21493.07,21440.00,21448.35,1387.35935,21466.72
2022-08-22 06:45:00,1.661140e+09,21449.10,21455.84,21407.25,21414.86,1228.30217,21480.50
2022-08-22 07:00:00,1.661141e+09,21413.67,21420.12,21341.91,21369.27,1964.35134,21435.72
2022-08-22 07:15:00,1.661142e+09,21369.27,21426.00,21352.86,21415.86,1538.36081,21433.76
2022-08-22 07:30:00,1.661143e+09,21414.60,21451.50,21392.63,21442.95,1522.13670,21428.66
...,...,...,...,...,...,...,...
2023-08-21 19:15:00,1.692634e+09,25950.87,26048.47,25944.71,26004.01,520.76171,NaN
2023-08-21 19:30:00,1.692635e+09,26004.01,26004.01,25980.00,25986.66,280.84530,NaN
2023-08-21 19:45:00,1.692636e+09,25986.67,26044.00,25975.63,26015.43,434.58646,NaN
2023-08-21 20:00:00,1.692637e+09,26015.42,26039.82,26002.08,26016.65,285.15295,NaN
2023-08-21 20:15:00,1.692638e+09,26016.64,26052.08,26008.02,26052.08,196.85752,NaN

In [27]:
np.log(data.close)

2022-08-22 06:30:00    21448.35
2022-08-22 06:45:00    21414.86
2022-08-22 07:00:00    21369.27
2022-08-22 07:15:00    21415.86
2022-08-22 07:30:00    21442.95
                         ...
2023-08-21 19:15:00    26004.01
2023-08-21 19:30:00    25986.66
2023-08-21 19:45:00    26015.43
2023-08-21 20:00:00    26016.65
2023-08-21 20:15:00    26052.08
Name: close, Length: 34996, dtype: float64